# Generated by Django 5.2 on 2025-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_fix_null_history_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='app_item_source_valid',
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('igdb', 'Internet Game Database'), ('openlibrary', 'Open Library'), ('googlebooks', 'Google Books'), ('hardcover', 'Hardcover'), ('comicvine', 'Comic Vine'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['tmdb', 'mal', 'mangaupdates', 'igdb', 'openlibrary', 'googlebooks', 'hardcover', 'comicvine', 'manual'])), name='app_item_source_valid'),
        ),
    ]
