# Generated by Django 5.2.2 on 2025-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_migrate_simkl_periodoc_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="runtime_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Runtime in minutes", null=True
            ),
        ),
    ]
