# Generated by Django 5.2 on 2025-09-25 02:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_migrate_simkl_periodoc_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rewatch', models.BooleanField(default=False, help_text='True if this is a rewatch')),
                ('progress_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('episode', models.ForeignKey(blank=True, help_text='Specific episode watched (for TV shows)', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.episode')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_date'],
                'indexes': [models.Index(fields=['user', '-watched_date'], name='app_watchhi_user_id_07f1c5_idx'), models.Index(fields=['item', '-watched_date'], name='app_watchhi_item_id_bd8919_idx')],
            },
        ),
    ]
