# Generated by Django 5.2.6 on 2025-11-30 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0052_alter_item_title"),
        ("app", "0053_item_release_datetime"),
    ]

    operations = []
