# Generated by Django 5.2.2 on 2025-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_migrate_simkl_periodoc_tasks"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0037_remove_user_home_sort_valid_alter_user_home_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("iso_8601", "ISO 8601"),
                    ("month_d_yyyy", "Month D, YYYY"),
                    ("d_mon_yyyy", "D Mon YYYY"),
                    ("m_d_yyyy", "M/D/YYYY"),
                    ("d_m_yyyy", "D/M/YYYY"),
                    ("dd_mm_yyyy", "DD.MM.YYYY"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("h_mm_ampm", "12-hour (h:mm AM/PM)"),
                    ("hh_mm_ampm", "12-hour, leading zero (hh:mm AM/PM)"),
                    ("hh_mm", "24-hour (HH:mm)"),
                    ("hh_mm_ss", "24-hour with seconds (HH:mm:ss)"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "home_sort__in",
                        ["recent", "upcoming", "completion", "episodes_left", "title"],
                    )
                ),
                name="home_sort_valid",
            ),
        ),
    ]
