# Generated by Django 5.2.2 on 2025-09-21 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_add_rating_sort_choice"),
        ("users", "0039_add_yyyy_mm_dd_date_format"),
    ]

    operations = []
