# Generated by Django 5.2.2 on 2025-09-21 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0041_add_time_left_sort_option"),
    ]

    operations = [
        # No operations needed - just updating the choices
    ]
