# Generated by Django 5.2.6 on 2025-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_remove_user_home_sort_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_pause_in_progress_enabled",
            field=models.BooleanField(
                default=False, help_text="Automatically pause stale in-progress items"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_pause_rules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Auto-pause rules with per-library week thresholds",
            ),
        ),
    ]
