# Generated by Django 5.2.6 on 2025-11-15 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_remove_user_home_sort_valid_and_more"),
        ("users", "0043_user_auto_pause_settings"),
    ]

    operations = []
