# Generated by Django 5.2.6 on 2025-11-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0053_item_release_datetime"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0045_remove_user_home_sort_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="game_logging_style",
            field=models.CharField(
                choices=[("sessions", "Sessions"), ("repeats", "Repeats")],
                default="repeats",
                help_text="How game entries are displayed on the History page",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "home_sort__in",
                        ["upcoming", "recent", "completion", "episodes_left", "title"],
                    )
                ),
                name="home_sort_valid",
            ),
        ),
    ]
