# Generated by Django 5.2.6 on 2025-11-30 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_user_clickable_media_cards"),
        ("users", "0047_user_media_direction_preferences"),
    ]

    operations = []
